version: 2
updates:
  - directory: /
    package-ecosystem: cargo
    target-branch: develop
    schedule:
      interval: daily
    groups:
      cargo:
        patterns:
          - "*"

  - directory: /
    package-ecosystem: docker
    target-branch: develop
    schedule:
      interval: daily
    groups:
      docker:
        patterns:
          - "*"

  - directory: /
    package-ecosystem: github-actions
    target-branch: develop
    schedule:
      interval: daily
    groups:
      github:
        patterns:
          - "*"

  - directory: /shelf-ui
    package-ecosystem: pnpm
    target-branch: develop
    schedule:
      interval: daily
    groups:
      npm:
        patterns:
          - "*"