apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shelf
  annotations:
    github.com/project-slug: 'klusoga-software/shelf'
spec:
  type: website
  owner: admins
  system: shelf
  lifecycle: experimental
  dependsOn:
    - resource:default/shelf-db

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: shelf-db
  description: Stores artifacts
spec:
  type: database
  owner: admins
  system: shelf

---

apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: shelf
spec:
  owner: admins
  domain: shelf

---

apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: shelf
spec:
  owner: admins
