### GET request to example server
POST http://localhost:6300/repo
Content-Type: application/json

{
  "name": "test",
  "repo_type": "Cargo",
  "public": false
}
###

### GET request to example server
GET http://localhost:6300/repo
###

###
DELETE http://localhost:6300/repo/6
###