apiVersion: v1
kind: Service
metadata:
  name: {{ include "shelf.fullname" . }}
  labels:
    {{- include "shelf.selectorLabels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.configuration.port }}
      targetPort: http
      name: http
  type: {{ .Values.service.type }}
  selector:
    {{- include "shelf.selectorLabels" . | nindent 4 }}