[package]
name = "migrator"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = {version = "0.8.2", features = ["runtime-tokio", "migrate", "postgres", "json"]}
tokio = {version = "1.41.0", features = ["full"]}